### PR TITLE
FEATURE | Add color name suggestion

### PR DESCRIPTION
**Pull request by j6s**
This adds color name suggestions based on the preset names.

screenrecord-2020-06-07_14 58 16 mp4

### CODE REVIEW

**Comment by j6s** [comment]
Don't merge yet, I have a cleanup coming up

**Comment by klickreflex** [comment]
Sweet!

**Comment by j6s** [comment]
:heavy_check_mark: Can be merged

**Comment by klickreflex** [comment]
Love it. Will rework the layout a bit soon, but it's a super nice addition.

**Pull request merged**
